{{- if .Values.configMap.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "profil3r.fullname" . }}-config
  labels:
    {{- with (include "profil3r.labels" . | fromYaml) }}
      {{ toYaml . | nindent 4 }}
    {{- end }}
data:
  {{- with .Values.configMap.data }}
    {{ toYaml . | nindent 2 }}
  {{- end }}
{{- end }}
