---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "profil3r.fullname" . }}-core
  labels:
{{- with (merge (dict "app.kubernetes.io/component" "core") (include "profil3r.labels" . | fromYaml)) }}
{{ toYaml . | nindent 4 }}
{{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8000
      protocol: TCP
      name: http
  selector:
{{- with (merge (dict "app.kubernetes.io/component" "core") (include "profil3r.selectorLabels" . | fromYaml)) }}
{{ toYaml . | nindent 4 }}
{{- end }}
