global:
  slack_api_url: 'https://hooks.slack.com/services/YOUR_WEBHOOK_URL'

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'web.hook'
  routes:
    - match:
        severity: critical
      receiver: 'critical-alerts'
    - match:
        severity: warning
      receiver: 'warning-alerts'

receivers:
  - name: 'web.hook'
    webhook_configs:
      - url: 'http://localhost:9093/api/v1/alerts'

  - name: 'critical-alerts'
    slack_configs:
      - channel: '#alerts'
        title: 'Critical Alert: {{ range .Alerts }}{{ .Annotations.summary }}{{ end }}'
        text: '{{ range .Alerts }}{{ .Annotations.description }}{{ end }}'
        color: 'danger'
        actions:
          - type: button
            text: 'View in Grafana'
            url: 'http://localhost:3001/d/profil3r-dashboard'
          - type: button
            text: 'View in Prometheus'
            url: 'http://localhost:9090/alerts'
    webhook_configs:
      - url: 'http://github-issue-creator:8080/create-issue'
        send_resolved: true
        http_config:
          basic_auth:
            username: '${GITHUB_USERNAME}'
            password: '${GITHUB_TOKEN}'

  - name: 'warning-alerts'
    slack_configs:
      - channel: '#monitoring'
        title: 'Warning: {{ range .Alerts }}{{ .Annotations.summary }}{{ end }}'
        text: '{{ range .Alerts }}{{ .Annotations.description }}{{ end }}'
        color: 'warning'
        actions:
          - type: button
            text: 'View in Grafana'
            url: 'http://localhost:3001/d/profil3r-dashboard'

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']
