# Pre-commit configuration for code quality and auto-fix hooks
repos:
  # Python formatting and linting
  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black
        language_version: python3
        files: \.py$
        args: [--line-length=88]

  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        files: \.py$
        args: [--profile=black]

  - repo: https://github.com/pycqa/flake8
    rev: 7.1.1
    hooks:
      - id: flake8
        files: \.py$
        args: [--max-line-length=88, --extend-ignore=E203, W503]
        exclude: ^modules/facebook_automation\.py$

  # JavaScript/TypeScript formatting and linting
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v9.15.0
    hooks:
      - id: eslint
        files: \.(js|ts|jsx|tsx)$
        args: [--fix]
        additional_dependencies:
          - eslint@^9.0.0
          - "@eslint/js@^9.0.0"
        exclude: ^(tools/cypress/e2e/.*\.cy\.js$|tools/js_tools/messenger_bot_framework/fbbot/test/.*|tools/__tests__/.*|tests/integration/node/.*|tools/web-ui/cypress/e2e/webui\.cy\.js$|tools/web-ui/script\.js$)

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        files: \.(js|ts|jsx|tsx|json|css|html|md|yml|yaml)$
        args: [--write]
        exclude: ^helm/profil3r/templates/.*\.ya?ml$

  # PHP formatting (optional - requires php-cs-fixer)
  - repo: local
    hooks:
      - id: php-cs-fixer
        name: PHP CS Fixer
        entry: bash
        language: system
        files: \.php$
        args:
          [
            -c,
            'if command -v php-cs-fixer >/dev/null 2>&1; then php-cs-fixer fix "$@"; else echo "php-cs-fixer not found, skipping PHP formatting"; fi',
            --
          ]

  # Ruby formatting (optional - requires rubocop)
  - repo: local
    hooks:
      - id: rubocop
        name: RuboCop
        entry: bash
        language: system
        files: \.rb$
        args:
          [
            -c,
            'if command -v rubocop >/dev/null 2>&1; then rubocop -A "$@"; else echo "rubocop not found, skipping Ruby formatting"; fi',
            --
          ]

  # General hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
        exclude: ^helm/profil3r/templates/.*\.ya?ml$
      - id: check-json
        exclude: ^(safety_baseline\.json|safety_scan_output\.json|node_modules/)
      - id: check-merge-conflict
      - id: debug-statements
      - id: mixed-line-ending
        args: [--fix=lf]

  - repo: local
    hooks:
      - id: lint-helm-yaml
        name: Lint rendered Helm YAML
        entry: bash scripts/lint-helm-yaml.sh
        language: system
        pass_filenames: false
        always_run: true
        stages: [commit, push]
        verbose: true

# Global configuration
default_stages: [pre-commit]
fail_fast: false
