version: '3.8' # Using a more recent version, like 3.8 or higher is good practice

services:
  backend:
    build: ./server
    ports:
      - "5000:5000" # Exposes backend on host port 5000
    environment:
      - MONGO_URI=mongodb://mongo:27017/metaMasReporterDB # Connects to mongo service on port 27017
      - PORT=5000
    volumes:
      - ./server:/app # Mounts the server directory for live updates (optional, good for dev)
      - /app/node_modules # Anonymous volume to prevent host node_modules from overwriting container's
    depends_on:
      - mongo # Ensures mongo starts before backend
    networks:
      - app-network

  frontend:
    build: ./client
    ports:
      - "3000:80" # Exposes frontend (Nginx) on host port 3000
    volumes:
      - ./client:/app # Mounts the client directory for live updates (optional, good for dev)
      - /app/node_modules # Anonymous volume
    depends_on:
      - backend # Ensures backend is available for API calls
    networks:
      - app-network

  mongo:
    image: mongo:latest # Using the latest official MongoDB image
    ports:
      - "27017:27017" # Exposes MongoDB on host port 27017 (optional, for direct access)
    volumes:
      - mongo-data:/data/db # Persists MongoDB data using a named volume
    networks:
      - app-network

volumes:
  mongo-data: # Defines the named volume for MongoDB data persistence

networks:
  app-network:
    driver: bridge # Defines a custom bridge network for services to communicate
