version: '3.8'

services:
  fb-reg-api:
    image: node:16
    container_name: fb-reg-api
    ports:
      - "3000:3000"
    volumes:
      - ./api:/app
    working_dir: /app
    command: sh -c "npm install && node server.js"
    environment:
      - NODE_ENV=development
