version: '3.8'
services:
  backend:
    build: .
    ports:
      - '5050:5050'
    environment:
      # test/demo password, not a real secret
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres
      - FLASK_SECRET_KEY=${FLASK_SECRET_KEY}
    depends_on:
      - db
    restart: always
    volumes:
      - ./fb_accounts.json:/app/tools/web-ui/fb_accounts.json
      - ./fb_reports.db:/app/tools/web-ui/fb_reports.db
      - ./:/app/tools/web-ui
  db:
    image: postgres:15
    environment:
      # test/demo password, not a real secret
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    restart: always
  frontend:
    image: nginx:alpine
    volumes:
      - ./:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - '3000:80'
    depends_on:
      - backend
    restart: always
