global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - 'alert_rules.yml'

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'profil3r-core'
    static_configs:
      - targets: ['profil3r-core:8080']
    metrics_path: '/api/health'
    scrape_interval: 30s
    scrape_timeout: 10s

  - job_name: 'js-tools'
    static_configs:
      - targets: ['js-tools:3000']
    metrics_path: '/api/health'
    scrape_interval: 30s
    scrape_timeout: 10s

  - job_name: 'osint-framework'
    static_configs:
      - targets: ['js-tools:8000']
    metrics_path: '/api/health'
    scrape_interval: 30s
    scrape_timeout: 10s

  - job_name: 'facebook-mass-messenger'
    static_configs:
      - targets: ['js-tools:4444']
    metrics_path: '/api/health'
    scrape_interval: 30s
    scrape_timeout: 10s

  - job_name: 'messenger-bot-framework'
    static_configs:
      - targets: ['js-tools:3000']
    metrics_path: '/api/health'
    scrape_interval: 30s
    scrape_timeout: 10s

  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    scrape_interval: 30s
    scrape_timeout: 10s

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']
    scrape_interval: 30s
    scrape_timeout: 10s

  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:80']
    scrape_interval: 30s
    scrape_timeout: 10s
