name: Code Quality Checks

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    name: Pre-commit hooks
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          tools: composer, php-cs-fixer

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
          bundler-cache: true

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit black isort flake8

      - name: Install Node.js dependencies
        run: npm install --prefix dependencies

      - name: Install RuboCop
        run: gem install rubocop

      - name: Cache pre-commit
        uses: actions/cache@v4
        with:
          path: ~/.cache/pre-commit
          key: pre-commit-${{ hashFiles('config/.pre-commit-config.yaml') }}

      - name: Run pre-commit
        run: pre-commit run --all-files --config config/.pre-commit-config.yaml

  python-quality:
    runs-on: ubuntu-latest
    name: Python Code Quality
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black isort flake8

      - name: Check formatting with Black
        run: black --check --diff .

      - name: Check import sorting with isort
        run: isort --check-only --diff .

      - name: Lint with flake8
        run: flake8 .

  javascript-quality:
    runs-on: ubuntu-latest
    name: JavaScript Code Quality
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Check formatting with Prettier
        run: npx prettier --check .

      - name: Lint with ESLint
        run: npx eslint . --ext .js,.ts,.jsx,.tsx

  php-quality:
    runs-on: ubuntu-latest
    name: PHP Code Quality
    steps:
      - uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          tools: composer, php-cs-fixer

      - name: Check formatting with PHP-CS-Fixer
        run: php-cs-fixer fix --dry-run --diff

  ruby-quality:
    runs-on: ubuntu-latest
    name: Ruby Code Quality
    if: ${{ hashFiles('**/*.rb') != '' }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'

      - name: Install RuboCop
        run: gem install rubocop

      - name: Lint with RuboCop
        run: rubocop --format github
